#!/bin/sh
t_i="`date +%s`"
mode=0
while :; do
	# detect sysline refresh interval
	dt="`ps x|grep 'sysline.*+[0-9]'|sed -e 's/.*+\([0-9][0-9]*\).*/\1/'`"
	test -n "$dt" || dt=60

	t="`date +%s`"
	tmp="`expr "$dt" - "$t" % "$dt"`"
	t_next="`expr "$t" + "$tmp"`"
	(
	case "$mode" in
	0)
		printf '['
		det="`ip -o addr	|grep -w inet \
					|grep ': e' \
					|awk '{print $2, $4}' \
					|cut -d/ -f1 \
					|sed -e 's/ /: /g'`"
		if [ -n "$det" ]; then
			printf '%s | ' "$det"
		fi
		det="`iwgetid -r`"
		if [ -n "$det" ]; then
			ip -o addr	|grep -w inet \
					|grep ': w' \
					|awk '{print $2, $4}' \
					|cut -d/ -f1 \
					|sed -e 's/ /: /g'
			printf '%s | ' "$det"
		fi
		batt	|tr -d \\n \
			|sed -e 's/ (.*)//g' -e 's/, Charging/↑/g' -e 's/, Discharging\(, input [0-9\.]\+ V\)\?/↓/g' -e 's/, Full/ ⏸/g' -e 's/, input / ⏦/g' -e 's/ temp / /g'
		printf '] '
		;;
	1)
		det="`foocal -M -p all --iconic -w`"
		test -n "$det" && printf '[%s]' "$det"
		;;
	esac
	) > $HOME/.who
	t="`date +%s`"
	dt="`expr "$t_next" - "$t"`"
	sleep "$dt"
	mode="`expr \( "$mode" + 1 \) % 2`"
done
