#!/bin/sh
export PULSE_SINK='alsa_output.pci-0000_00_14.2.analog-stereo'
EXPECTED_PORT='analog-output-headphones'

t_i="`date +%s`"
mode=0
n_keyboards="`lsusb -v 2>/dev/null|grep Keyboard|wc -l`"
while :; do
	case "`date +%d`" in
	29)
		divisor=5
		;;
	*)
		divisor=4
	esac

	# set correct port - FIXME: this should only be done at home
	if is-at-home; then
		pa-set-sink-port $PULSE_SINK $EXPECTED_PORT
		nmcli d|grep wlan0|grep -w connected >/dev/null && nmcli device disconnect wlan0
	fi

	# load esound as a system daemon, but only when at home
	if is-at-home; then
		for module in module-esound-protocol-tcp module-native-protocol-tcp; do
		(pacmd list-modules|grep -q "$module") || pacmd load-module "$module" 'auth-ip-acl=127.0.0.1;192.168.0.0/24' auth-anonymous=1
		done
	else
		for module in module-esound-protocol-tcp module-native-protocol-tcp; do
		(pacmd list-modules|grep -q "$module") && pacmd unload-module "$module"
		done
	fi

	# try to detect new keyboards - XXX THIS IS DANGEROUS if any key is pressed while xmodmap does its thing
	n_keyboards_new="`lsusb -v 2>/dev/null|grep Keyboard|wc -l`"
	if [ -z "$n_keyboards" ] || [ "$n_keyboards_new" -gt "$n_keyboards" ]; then
		# FIXME we also need to reset mousekeys but I don't know how to do it
		fix-xmodmap
		n_keyboards="$n_keyboards_new"
	elif [ "$n_keyboards_new" -lt "$n_keyboards" ]; then
		n_keyboards="$n_keyboards_new"
	fi

	# kill unwanted programs
	killall update-manager >/dev/null 2>&1

	# detect sysline refresh interval
	dt="`ps x|grep 'sysline.*+[0-9]'|sed -e 's/.*+\([0-9][0-9]*\).*/\1/'`"
	test -n "$dt" || dt=60

	# detect NFS server crash
	grep -w nfs /etc/fstab|cut -d: -f1|sort|uniq | while read a; do
		nfsup "$a" >/dev/null || paplay --volume 16384 /software/sndkit/data/wav/alarm.wav
	done

	t="`date +%s`"
	tmp="`expr "$dt" - "$t" % "$dt"`"
	t_next="`expr "$t" + "$tmp"`"
	(
	case "$mode" in
	0)
		printf '['
		det="`ip -o addr	|grep -w inet \
					|grep ': e' \
					|awk '{print $2, $4}' \
					|cut -d/ -f1 \
					|sed -e 's/ /: /g'`"
		if [ -n "$det" ]; then
			printf '%s | ' "$det"
		fi
		det="`iwgetid -r`"
		if [ -n "$det" ]; then
			ip -o addr	|grep -w inet \
					|grep ': w' \
					|awk '{print $2, $4}' \
					|cut -d/ -f1 \
					|sed -e 's/ /: /g'
			printf '%s | ' "$det"
		fi
		batt	|tr -d \\n \
			|sed -e 's/ (.*)//g' -e 's/, Charging/↑/g' -e 's/, Discharging\(, input [0-9\.]\+ V\)\?/↓/g' -e 's/, Full/ ⏸/g' -e 's/, input / ⏦/g' -e 's/ temp / /g'
		printf '] '
		;;
	1)
		det="`foocal -M -p all --iconic -w`"
		test -n "$det" && printf '[%s]' "$det"
		;;
	2)
		printf "[%s]" "`temps -s`"
		;;
#	3)
#		df  -P -m|awk '{print $1 "\t" $5 "\t" $4}'|grep /dev\\\|:|sort -k2 -r -n|uniq
#		;;
	3)
		test -n "` /usr/local/sbin/mailq`" && echo 'You have unsent mail'
		if [ -n "$DISPLAY" ]; then
			test -z "`xlsclients|grep ' evolution$'`" && echo "Evolution is not running"
		fi
		;;
	4)
		printf 'PAY PHONE BILL TODAY'
		;;
	esac
	) > $HOME/.who
	t="`date +%s`"
	dt="`expr "$t_next" - "$t"`"
	sleep "$dt"
	mode="`expr \( "$mode" + 1 \) % $divisor`"
done
