#!/bin/sh

# Restrict virtual memory
ulimit -S -v 20000000
ulimit -H -v 20050000

# Restrict resident set size, if possible
ulimit -S -m 2048000
ulimit -H -m 3276800

ulimit -H -c 0
unset TERMCAP STY
exec /usr/bin/google-chrome "$@"
