#!/bin/sh
# A small script to run pidgin more safely when we're trying out
# potentially unsafe prpl's

# Compressor option: gzip
#compress="gzip -9"
#suffix=.gz

# Compressor option: xz (NOTE: DO NOT use -7 or higher! default is already the highest safe compression ratio)
compress=xz
suffix=.xz

# Make sure pidgin is there
pidgin="`which pidgin`"
if [ -z "$pidgin" ]; then
	echo "pidgin not found" >&2
	exit 1
fi

# Figure out where we should back things up to
tag="`date +'%Y%m%d%H%M%S'`"
purple="$HOME/.purple"
dir="$purple/debug/$tag"
mkdir -p "$dir"
cd "$dir" || exit $?

add_timestamp=`which tai64n`
test -z "$add_timestamp" && add_timestamp=cat

# Back up XML files (esp. accounts.xml)
(cd "$purple" && ls -1 *.xml) | while read xml; do
	$compress < "$purple/$xml" > "$dir/$tag.$xml$suffix"
done

# Force debug mode and save the debug output, and make sure core is dumped if it crashes
if [ -z "`which multilog`" ]; then

ulimit -c unlimited
$pidgin -d "$@" |$add_timestamp |$compress > $debug
st=$?
test -f core && mv core "$core"

else

( ulimit -c unlimited; $pidgin -d "$@" ) |multilog t s16777215 .
st=$?
[ cat != "$compress" ] && $compress current *.s *.u

fi
exit $st
