#!/bin/sh
# A small script to report whether pidgin is running and if so report
# - its pid
# - whether it's run through the "gaim" wrapper script
# - which locale it's running in
# - which directory it's running in
# - how much space is being used by the debug log(s)

pidgin="`killall -v -0 pidgin 2>&1 |cut -d\( -f2 |cut -d\) -f1`"
case "$pidgin" in
""|*"no process found")
	echo "pidgin not running" >&2
	exit 1
esac

cd "/proc/$pidgin/cwd" || exit 2
cd "`/bin/pwd`"

lang="`grep -z ^LANG= /proc/$pidgin/environ |cut -d= -f2-`"
lc_all="`grep -z ^LC_ALL= /proc/$pidgin/environ |cut -d= -f2-`"
test -n "$lc_all" && lang="$lc_all"
fmt='%-32s : %s\n'

if [ -f current ]; then
	echo "pidgin ($pidgin) started with gaim wrapper in multilog mode"
	echo
	printf "$fmt" "locale" "$lang"
	printf "$fmt" "debug directory" "`pwd`"
	printf "$fmt" "current debug log (uncompressed)" "`du -h current|awk '{print $1}'`"
	if [ "`ls *.s *.u 2>/dev/null |wc -l`" -gt 0 ]; then
		printf "$fmt" "old debug log(s) (uncompressed)" "`du -h --total *.s *.u 2>/dev/null |tail -1 |awk '{print $1}'`"
	fi
else
	gaim=
	case "`pwd`" in
	*/.purple/debug/*)
		if [ -f debug.log ]; then
			gaim=uncompressed
		else
			if [ "`ls debug.log.* 2>/dev/null |wc -l`" -eq 1 ]; then
				gaim=compressed
			fi
		fi
	esac
	if [ -n "$gaim" ]; then
		echo "pidgin ($pidgin) probably started with gaim wrapper in non-multilog mode"
		echo
		printf "$fmt" "locale" "$lang"
		printf "$fmt" "debug directory" "`pwd`"
		printf "$fmt" "current debug log ($gaim)" "`du -h debug.log* |awk '{print $1}'`"
	else
		echo "pidgin ($pidgin) started without using the gaim wrapper"
		echo
		printf "$fmt" "locale" "$lang"
		printf "$fmt" "directory" "`pwd`"
	fi
fi
if [ -f stderr.log ]; then
	printf "$fmt" "stderr log (uncompressed)" "`du -h stderr.log 2>/dev/null |tail -1 |awk '{print $1}'`"
elif [ "`ls stderr.log* 2>/dev/null |wc -l`" -gt 0 ]; then
	printf "$fmt" "stderr log (compressed)" "`du -h stderr.log.* 2>/dev/null |tail -1 |awk '{print $1}'`"
fi
